FIELD_WINDOW_HEIGHT = 480
FIELD_WINDOW_WIDTH = 640
FIELD_WINDOW_FULLSCREEN = False

FIELD_WINDOW_SCALE_SPEED = 10
FIELD_WINDOW_SCALE_DEFAULT = 1
FIELD_WINDOW_SCALE_MIN = -20
FIELD_WINDOW_SCALE_MAX = 20


FIELD_WINDOW_CAMERA_MOVE_BUTTON = 4